Repository rogerinn/hermes, pull requests merged in 2023-02, with the labels that each got.

#33 Remove command npm
  .github/workflows/publish-npm.yml
Labels: CD/CI

#36 Add stage config npm
  .github/workflows/publish-npm.yml
Labels: CD/CI

#42 Fix shields
  README.md
  package.json
Labels: bug, documentation

#44 Staging
  README.md
  package.json
Labels: bug, documentation

#45 Docs external documentation
  README.md
  package.json
Labels: documentation, enhancement

#47 Staging
  README.md
  package.json
Labels: documentation, enhancement

#48 Docs revision
  README.md
  package.json
Labels: documentation, enhancement

#49 Docs revision
  README.md
  package.json
Labels: documentation, enhancement

#50 Dev
  README.md
  package.json
Labels: documentation, enhancement

#51 Staging
  README.md
  package.json
Labels: documentation, enhancement, CD/CI

#52 Ci npm
  .npmrc
  package.json
Labels: CD/CI

#55 Ci/name
  package.json
Labels: CD/CI

#59 ci: add github token
  .github/workflows/publish-npm.yml
Labels: bug, CD/CI

#62 fix: revert stable version
  .github/workflows/publish-npm.yml
  .npmrc
  package.json
Labels: CD/CI

#65 Docs observer
  README.md
  package.json
Labels: bug, documentation, enhancement

#66 Docs table of contents
  README.md
  package.json
Labels: documentation, enhancement

#67 Docs branch flow image
  README.md
  package.json
Labels: documentation, enhancement

#68 Docs refactor image
  README.md
  package.json
Labels: bug, documentation

#69 Docs/architecture
  README.md
  package.json
Labels: bug, documentation, enhancement

#70 Docs refactor
  README.md
  package.json
Labels: bug, documentation

#71 Docs add community
  README.md
  package.json
Labels: documentation, enhancement

#72 Docs thanks
  README.md
  package.json
Labels: documentation, enhancement

#73 Docs fix
  README.md
  package.json
Labels: bug, documentation

#75 Staging
  README.md
  package.json
Labels: documentation, enhancement, CD/CI

#76 Fix license correction
  package.json
Labels: bug, CD/CI

#77 Docs motivations
  README.md
  package.json
Labels: documentation, enhancement

#78 Docs features
  README.md
  package.json
Labels: documentation, enhancement

#79 Docs use hermes
  README.md
  package.json
Labels: bug, documentation, enhancement

#80 Docs tech
  README.md
  package.json
Labels: documentation, enhancement

#82 Staging
  README.md
  package.json
Labels: documentation, enhancement, CD/CI

#83 Docs refactor
  README.md
  package.json
Labels: bug, documentation

#88 Dev
  .gitignore
  README.md
  package-lock.json
  package.json
  proto/notes.proto
  proto/notes.ts
  proto/teste/Empty.ts
  proto/teste/Note.ts
  proto/teste/NoteFindRequest.ts
  proto/teste/NoteFindResponse.ts
  proto/teste/NoteListResponse.ts
  proto/teste/Notes.ts
  src/application/config/adapters/gRPC-adapter.ts
  src/application/config/protocols/add-service-protocol.ts
  src/application/config/protocols/client-protocol.ts
  src/application/config/protocols/grpc-protocol.ts
  src/application/config/protocols/handlers-protocol.ts
  src/application/config/protocols/http-manager-protocol.ts
  src/application/config/protocols/index.ts
  src/application/config/protocols/load-proto-protocol.ts
  src/application/config/protocols/start-server-protocol.ts
  src/presentation/controller-server.ts
  src/presentation/protocol/controller-protocol.ts
  src/presentation/protocol/index.ts
  src/server.ts
  src/server2.ts
  tsconfig.json
Labels: documentation, enhancement, CD/CI

#89 Staging
  .gitignore
  README.md
  package-lock.json
  package.json
  proto/notes.proto
  proto/notes.ts
  proto/teste/Empty.ts
  proto/teste/Note.ts
  proto/teste/NoteFindRequest.ts
  proto/teste/NoteFindResponse.ts
  proto/teste/NoteListResponse.ts
  proto/teste/Notes.ts
  src/application/config/adapters/gRPC-adapter.ts
  src/application/config/protocols/add-service-protocol.ts
  src/application/config/protocols/client-protocol.ts
  src/application/config/protocols/grpc-protocol.ts
  src/application/config/protocols/handlers-protocol.ts
  src/application/config/protocols/http-manager-protocol.ts
  src/application/config/protocols/index.ts
  src/application/config/protocols/load-proto-protocol.ts
  src/application/config/protocols/start-server-protocol.ts
  src/presentation/controller-server.ts
  src/presentation/protocol/controller-protocol.ts
  src/presentation/protocol/index.ts
  src/server.ts
  src/server2.ts
  tsconfig.json
Labels: bug, documentation, CD/CI, feature

#93 Docs technologies table
  README.md
  package.json
Labels: bug, documentation

#94 Docs revision
  README.md
  package.json
Labels: bug, documentation

#97 Staging
  README.md
  package.json
Labels: bug, documentation, enhancement, CD/CI, feature

#100 Fix/entryfile
  package.json
Labels: bug, CD/CI

#101 Staging
  dist/proto/notes.proto
  dist/src/client.d.ts
  dist/src/client.d.ts.map
  dist/src/client.js
  dist/src/client.js.map
  dist/src/index.d.ts
  dist/src/index.d.ts.map
  dist/src/index.js
  dist/src/index.js.map
  index.js
  package.json
  src/index.ts
Labels: bug, CD/CI

#102 Fix/entryfile
  dist/src/index.js
  dist/src/index.js.map
  package-lock.json
  package.json
  src/index.ts
  tsconfig.json
Labels: bug, CD/CI

#105 Fix/entryfile
  dist/src/index.d.ts
  dist/src/index.d.ts.map
  dist/src/index.js
  dist/src/index.js.map
  package-lock.json
  package.json
  src/index.ts
Labels: bug, CD/CI

#110 Staging
  dist/src/index.d.ts
  dist/src/index.d.ts.map
  dist/src/index.js
  dist/src/index.js.map
  package.json
  src/index.ts
Labels: bug, CD/CI

#111 Docs: discord link
  README.md
  package.json
Labels: bug, documentation

#112 Dev
  README.md
  package.json
Labels: bug, CD/CI
